name: @NAME@
version: @VERSION@
description: Manages donation benefits
author: EdGruberman (ed@rjump.com)
main: edgruberman.bukkit.donations.Main
commands:
    'donations:history':
        aliases: [donations, history, donations.history]
        description: Show donation history
        permission: donations.history
        usage: /<command>[ <Page>][ <Donator>]
    'donations:benefits':
        aliases: [benefits, donations.benefits]
        description: Show package/benefit detail
        permission: donations.benefits
        usage: /<command>[ <Package>]
    'donations:process':
        aliases: [donations.process]
        description: Process a donation
        permission: donations.process
        usage: /<command> <Donator> <Amount>[ <When>]
    'donations:apply':
        aliases: [donations.apply]
        description: Dispatch commands for package, benefit, or command
        permission: donations.apply
        usage: /<command> <Player> <Package>[ <Benefit>[ <Command>]]
    'donations:undo':
        aliases: [donations.undo]
        description: Revert applied package, benefit, or command for donation
        permission: donations.undo
        usage: /<command> <Donation> <Package>[ <Benefit>[ <Command>]]
    'donations:reset':
        aliases: [donations.reset]
        description: Remove any package, benefit, or command that is not for donation
        permission: donations.reset
        usage: /<command> <Donation> <Package>[ <Benefit>[ <Command>]]
    'donations:reload':
        description: Reload Donations plugin
        permission: donations.reload
        usage: /<command>
permissions:
    donations.info:
        description: Can use basic information commands
        default: true
        children:
            donations.history: true
            donations.benefits: true
    donations.admin:
        description: Can use all commands
        default: op
        children:
            donations.info: true
            donations.process: true
            donations.undo: true
            donations.reload: true