name: Benefits
version: @VERSION@
description: Manages player benefits for contributions
author: EdGruberman (ed@rjump.com)
main: edgruberman.bukkit.benefits.Main
commands:
  'benefits:contributions':
    aliases: [contributions, benefits.contributions]
    description: Show contribution history
    permission: benefits.history
    usage: '§f-> §7Usage: §b/<command> §3[§opage§3] [§ocontributor§3]'
  'benefits:benefits':
    aliases: [benefits]
    description: Show package/benefit detail
    permission: benefits.benefits
    usage: '§f-> §7Usage: §b/<command> §3[§opackage§3]'
  'benefits:process':
    aliases: [process, benefits.process]
    description: Record and apply a contribution
    permission: benefits.process
    usage: '§f-> §7Usage: §b/<command> §3§ocontributor amount §3[§owhen§3]'
  'benefits:undo':
    aliases: [undo, benefits.undo]
    description: Revert applied package, benefit, or command from contribution
    permission: benefits.undo
    usage: '§f-> §7Usage: §b/<command> §3§ocontribution package §3[§obenefit§3]§o §3[§ocommand§3]'
  'benefits:assign':
    aliases: [assign, benefits.assign]
    description: Manually assign package, benefit, or command tocontributionn
    permission: benefits.assign
    usage: '§f-> §7Usage: §b/<command> §3§ocontribution package §3[§obenefit§3]§o §3[§ocommand§3]'
  'benefits:sandbox':
    aliases: [sandbox, benefits.sandbox]
    description: Toggle sandbox mode on or off
    permission: benefits.sandbox
    usage: '§f-> §7Usage: §b/<command> §3[§bon§3|§boff§3]'
  'benefits:register':
    aliases: [register, benefits.register]
    description: Associate a contribution origin (e-mail) with a player
    permission: benefits.register
    usage: '§f-> §7Usage: §b/<command> §3§oorigin §3[§oplayer§3]'
  'benefits:reload':
    description: Reload Benefits plugin
    permission: benefits.reload
    usage: '§f-> §7Usage: §b/<command>'
permissions:
  benefits.user:
    description: Can use basic features
    default: true
    children:
      benefits.history: true
      benefits.benefits: true
  benefits.admin:
    description: Can use all features
    default: op
    children:
      benefits.user: true
      benefits.process: true
      benefits.undo: true
      benefits.assign: true
      benefits.sandbox: true
      benefits.register: true
      benefits.reload: true
  benefits.history:
    description: Can use history command
    default: false
  benefits.benefits:
    description: Can use benefits command
    default: false
  benefits.process:
    description: Can use process command
    default: false
  benefits.undo:
    description: Can use undo command
    default: false
  benefits.assign:
    description: Can use assign command
    default: false
  benefits.sandbox:
    description: Can use sandbox command
    default: false
  benefits.register:
    description: Can use register command
    default: false
  benefits.reload:
    description: Can use reload command
    default: false